on:
  workflow_dispatch:
  schedule:
    - cron: '00 9 * * *'

jobs:
  buildPulse-digest:
    runs-on: ubuntu-latest
    name: Send BuildPulse digest to Discord
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send Digest
        uses: ./ # Uses an action in the root directory
        with:
          buildPulse-api-token: ${{ secrets.BUILDPULSE_API_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_BUILDPULSE_WEBHOOK }}